#! /bin/sh
# /etc/init.d/EAS-RV12-Startup
#

# Scipt as follows

### Neccessary Start-up items ###

mkdir /logs
# This will likely emit an error, ignore it. #
# This guarentees that the working directory for this file will exist #

# This variable determines whether the crypt will use the log function or not #
logging=true

### Functions ###

log () {
# This is a generic log function so as to avoid a "D.R.Y." infraction.#
# The function pushes a message to a log file, should it be needed later. #
# If variable "logging", located in "Necessary Start-up Items" is set to false... #
# then this function will still be ran, but its abilities shall be left unutilized.#
	if $logging
	then
		for var in "$@"
		do
			echo "$var"  >> /logs/RV12.log
		done
	fi
}

init () {
# This is a generic initiation function so as to avoid a "D.R.Y." infraction. #
# The function trys to call the scripts requested via string input. #
# I personnaly suggest against this function due to possible user error. #
# The fucntion will run all inputted scripts followed by a delay as defined by "delay" #
	for var in "$@"
	do
		log "$var"
		$var &
	done
}

init "/etc/init.d/testenv/t1" "/etc/init.d/testenv/t2" "/etc/init.d/testenv/t3" "/etc/init.d/testenv/t4" "/etc/init.d/testenv/t5"

##init "/EASCoding/Strangj/workspace/eas_bbb_version1/beta_daq_test.v2.exe"
